### ISSUE TITLE
Root filesystem should be read-only to prevent corruption due to loss of power

### ISSUE THREAD

**Issue by cimryan** [cimryan/teslausb#14]
Allegedly this is a thing that can happen to Raspberry Pis.

**Comment by rtgoodwin** [comment]
Can confirm this has happened with other Pi projects in the past, and I think it's the reason I've had the Zero not come up as a drive once or twice. (Either rough filesystem state or something similar prevents it coming ready.) On a 5 stop drive yesterday (6 total drives), it didn't come up twice and start recording. I have yet to recreate it sitting in the garage (of course) where I could SSH in to figure it out.

**Comment by cimryan** [comment]
https://github.com/cimryan/teslausb/commit/7dfc9de59cc22649876dfb141bf46953a0c27cef
