### ISSUE TITLE
May I use Raspberry Pi 3+ to do this?

### ISSUE THREAD

**Issue by ffllc** [cimryan/teslausb#142]
I had Raspberry Pi 3+ ,so may I use Raspberry Pi 3+ to do this?

**Comment by hilli** [comment]
Nope. Raspberry Pi Zero only. The other Pi's have a USB hub on them, which ruins the USB-To-Go.

**Comment by ffllc** [comment]
copy that. thanks.

**Comment by rreynier** [comment]
Is there any ways to make this possible on other raspberry's? Using some other approach?

**Comment by hilli** [comment]
@rreynier, not on the Pi's. But I just found this thing (Alas, I haven't tried it):

https://www.olimex.com/Products/OLinuXino/Home-Server/Pioneer-FreedomBox-HSK/open-source-hardware

It is an ARM7 CPU, 1GB RAM, has USB On-The-Go support _and_ 2 USB 2.0 ports. No wifi though, but you can use a USB WiFi dongle for that. I also like the build in battery that acts a an UPS - Handy for when the Tesla shuts off the power, allowing for a graceful shutdown of the thing.
