### ISSUE TITLE
Create TeslaCam directory as part of setup script

### ISSUE THREAD

**Issue by firedfly** [cimryan/teslausb#37]
`setup-teslausb` should be able to mount the cam drive and create the `TeslaCam` directory automatically.  This would eliminate several steps from the setup instructions as the pi would not need to be connected to a PC before being used in a Tesla.

I can make this change tomorrow if there are no objections about its usefulness.

**Comment by rtgoodwin** [comment]
I've said to myself probably 15 times "remember to add that" and forgotten. Go for it. :)

**Comment by cimryan** [comment]
Merged!
