### ISSUE TITLE
No CAM drive mounting on windows

### ISSUE THREAD

**Issue by neondemon** [cimryan/teslausb#38]
CAM drive not mounting on windows (multiple machines) fresh install

**Comment by cimryan** [comment]
Did you set up the Pi using a Windows, Linux, or Mac OS?

**Comment by neondemon** [comment]
initial windows, then SSH

**Comment by rtgoodwin** [comment]
Is the Archive server/IP reachable from your Pi? What are the last lines of /tmp/archive-teslacam-clips.log and archive-loop.log?

**Comment by neondemon** [comment]
i just did a format and reinstall form scratch, and it works.... im assuming i screwed up something simple and dumb? or the edit to setup-teslausb fixed it?

**Comment by cimryan** [comment]
Glad to hear you got it working.
