### ISSUE TITLE
Split partitions for media?

### ISSUE THREAD

**Issue by allanak** [cimryan/teslausb#4]
Since you decided to fork, I hope you don't mind I'm opening an issue for you since you made an ideas section of your readme :) A few recent reddit posts on v9 seem to indicate multiple partitions on a USB stick give the ability to have one partition for the "teslacam" storage and a separate one for media/music.

Assuming that split partitioning works, It'd be a great addition here to also sync down a media library to a secondary mountpoint. I just ordered a pi and won't be able to try til it gets here. Happy to try and do this myself and submit a PR

**Comment by cimryan** [comment]
Good luck!

**Comment by cimryan** [comment]
I got this working: 98cecb4cbfa0692495a742b3bb4b74bbf7c90622
