### ISSUE TITLE
script problems

### ISSUE THREAD

**Issue by odintorg** [cimryan/teslausb#44]
Got Wifi working, but can't get setup-teslausb to run to completion. On second run it stopped because /root/bin existed. Deleted that. Then it stopped because /backingfiles existed. Deleted both /root/bin and its contents, and /backingfiles, and third try got me down to where it downloaded /root/remountfs_rw, and then it quite with the error "The location 65333952 is outside of the device /dev/mmcblk0.

Don't know what to change to fix that..

**Comment by cimryan** [comment]
The setup-teslausb script doesn't handle rerunning, yet. For now, you'll probably achieve fastest success by reflashing.
