### ISSUE TITLE
USB fs read only when root is read only

### ISSUE THREAD

**Issue by jab416171** [cimryan/teslausb#72]
I should start by saying I haven't exactly run the scripts in this repo, but I ran most of what's in the reddit thread. When I set the root fs to read only in fstab, the usb storage becomes read only too, and thus the car is unable to record any dash cam footage. What do I need to do to make the usb storage writable while keeping the root filesystem read only, to avoid corruption?

**Comment by cimryan** [comment]
You need to create another partition, so you have something to mount, separately from the root partition, so you can specify read-only for one and read-write for the other.

If you want to see how this works look at create-backingfiles-partition.sh.

If you want to get this working quickly you'll save time by just following the instructions in this repo.
