### ISSUE TITLE
Suggest checking the archive name value to see if it's an IP to bypass that bit if needed.

### ISSUE THREAD

**Issue by cimryan** [cimryan/teslausb#8]
> Not all hosts are discoverable by name; for example mine isn't. So the script lines that find the share server IP by resolving the hostname won't work for me. 

From https://github.com/cimryan/teslausb/issues/5

**Comment by cimryan** [comment]
I think the archiveservername can be specified as an IP address when using the setup-teslausb script. If an IP address is specified that address will be written into /etc/fstab and /root/bin/archiveloop.

Does that address this issue?

**Comment by cimryan** [comment]
That line will set archiveserverip to the value of $archiveserver if $archiveserver contains an IP address.

**Comment by rtgoodwin** [comment]
With current code, if an IP is set as the archivename, the fstab is written out as `///ShareName`, so it does seem like it's eating the IP address somehow.
